// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      // ignore: do_not_use_environment
      const flavor = String.fromEnvironment('FLAVOR');
      return flavor == 'prod' ? prod : dev;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const dev = FirebaseOptions(
    apiKey: 'AIzaSyC6Bydu9OtRu93EB7izNWr9gFixVpJM6sc',
    appId: '1:193204818605:web:75e857b289a395086aac24',
    messagingSenderId: '193204818605',
    projectId: 'n-sneaker-development',
    authDomain: 'n-sneaker-development.firebaseapp.com',
    storageBucket: 'n-sneaker-development.appspot.com',
    measurementId: 'G-4LY6MKL64N',
  );

  static const prod = FirebaseOptions(
    apiKey: 'AIzaSyAB4Is_RRyO0YsxLpoLwa3dNZ45kbkhx0g',
    authDomain: 'n-sneaker-production.firebaseapp.com',
    projectId: 'n-sneaker-production',
    storageBucket: 'n-sneaker-production.appspot.com',
    messagingSenderId: '96386266943',
    appId: '1:96386266943:web:6bb8051017997319afc58a',
    measurementId: 'G-W187X9L3X8',
  );
}
